name: test

on:
  push:
    branches:
    - main
    - 'test/staging'
    paths:
    - '.github/workflows/test.yml'
  create:
    branches:
    - 'test/staging'
    paths:
    - '.github/workflows/test.yml'
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'create' && github.ref == 'refs/heads/test/staging')
    steps:
    - name: test Display GitHub event context
      run: echo "eventname:${{ github.event_name }},ref:${{ github.ref }},refname:${{ github.ref_name }}"
    

