name: test

on:
  create:
    branches: ["test/staging"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'create' && github.ref == 'refs/heads/test/staging')
    steps:
    - name: Display GitHub event context
      run: echo "eventname:${{ github.event_name }}ref:${{ github.ref }}refname:${{ github.ref_name }}${{ toJson(github.event) }}"
    

