name: test

on:
  create:
    branches:
    - 'test/staging'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display GitHub event context
      run: echo "${{ toJson(github.event) }}"
    

