name: trager

on:
  push:
    branches:
    - main
    - 'test/staging'
    paths:
    - '.github/workflows/trager.yml'
  create:
    branches:
    - 'test/staging'
    paths:
    - '.github/workflows/trager.yml'
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'create' && github.ref == 'refs/heads/test/staging')
    steps:
    - name: trager Display GitHub event context
      run: echo "eventname:${{ github.event_name }},ref:${{ github.ref }},refname:${{ github.ref_name }}"
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }} 
    - name: Fetch all branches
      run: git fetch --all
    - name: Check for modifications
      id: check_diff
      run: |
        # Specify the paths you want to monitor
        monitored_paths="[.github/workflows/trager.yml,tragger_version]"

        # Get the difference against the main branch (replace 'main' with your base branch if different)
        if git diff --name-only origin/main | grep -qE "$monitored_paths"; then
          echo "Changes detected in monitored paths."
          echo "proceed=true" >> $GITHUB_ENV
        else
          echo "No changes detected in monitored paths."
          echo "proceed=false" >> $GITHUB_ENV
        fi

    - name: Continue or abort the CI process
      if: env.proceed == 'true'
      run: |
        echo "Running CI processes..."
        # Your CI steps go here
        # For example, running tests or building the project

    - name: Abort CI process
      if: env.proceed == 'false'
      run: |
        echo "Aborting CI process as no relevant changes were detected."
        exit 0  # Exit gracefully

